test_products = [
    "Diamond Light Candy 6gx24pcsx12boxes",
    "Ice Lolly Jelly 14gx30pcsx20boxes",
    "Jelly cup in Monkey Jar 13gx100pcsx6jars",
    "Mini Cup Jelly (Panda Bag) 13gx100pcsx6jars",
    "Jelly cup in Koala Jar 13gx100pcsx6jars",
    "Mini cup Jelly (Duck Jar) 13gx100pcsx6jars",
    "Mini cup Jelly (Owl Jar) 13gx100pcsx6jars",
    "Mini cup Jelly (Hippo Jar) 13gx100pcsx6jars",
    "Mini Jelly cup in (Trush can) 13gx100pcsx6jars",
    "Mini cup jlly (Benben bear Jar) 13gx100pcsx6jars",
    "Winx Spray Candy 30gx12pcsx12boxes",
    "Baby bottle(Whistle candy) 9gx100pcsx6jars",
    "COBRA GUMMY 16g*24pcs*12boxes",
    "HOTDOG GUMMY 16g*24pcs*12boxes",
    "5D Fruits Gummy Candy 10gx50pcsx12jars",
    "Dinosaur Gummy 8gx12pcsx20boxes",
    "Super Car Gummy 20gx20pcsx12boxes",
    "Toy and Jelly 30gx50pcsx6jars",
    "Snake jelly 35gx48pcsx6jars",
    "Crocodile jelly 35gx48pcsx6jars",
    "2in1 Crazy Hair Candy 20gx20pcsx12boxes",
    "Cola Tin Spray Candy 30mlx24pcsx12boxes",
    "Cow Eyes Gummy 7gx60pcsx12jars",
    "Bear Pudding 40gx20pcsx18tray",
    "EYE CANDY STAND 3,5 GX24X8",
    "EYEBALL CANDY SATND 3,5 GX24X8",
    "Biberon Liquid Candy 30mlX30pcsx18boxes",
    "Long CC Stick Candy 4gx50pcsx40bags",
    "Snake Gummy 8gx30pcsx20boxes",
    "Birthday Cake Gummy 12gx20pcsx12boxes",
    "Jelly (Skeleton shape) 35gx55pcsx6jars",
    "Mini Jackpot Gum Ball 20gx12pcsx 12boxes",
    "Bear Jelly 35gx30pcsx12boxes",
    "Butterfly Jelly 35gx30pcsx12boxes",
    "3in1 Squeeze Candy 45gx12pcsx12boxes",
    "Ice Cream 3in1 16gx24pcsx10boxes",
    "Mouse Candy 6gx30pcsx24trays",
    "Rabbit Candy 6gx30pcsx24trays",
    "Fruits Press Candy 10gx30pcsx20boxes",
    "Super Sour Hard Candy 12gx24pcsx20boxes",
    "Big Burger Gummy 32gx8pcsx8boxes",
    "Mini Lollipop Shooter 3gx12pcsx 24boxes",
    "Big Foot lollipop+Sour Powder Candy 7.5gx30pcsx24boxes",
    "Roll Gum 7g×24pcs×24boxes",
    "Twins eyeball Gummy 4g*100pcs*12jars",
    "Stretch frog candy 5gx12pcsx6boxes",
    "Skull Candy + bear Candy 6gx60pcsx12jars",
    "Microphone pudding 33gx30pcsx12jars",
    "Mega sour jam 30gx20pcsx12boxes",
    "Bracelet Candy 10gx48pcsx12boxes UNI",
    "Lighting New Spray Candy 25gx30pcsx20boxes",
    "Toilet Candy 13gx24pcsx12boxes",
    "Biberon liquit candy 40g*30pcs*16boxes",
    "Stick grape gummy 10g*30pcs*20jars",
    "stick eyeball gummy 10g*30pcs*20jars",
    "DEVIL GUMMY 8g*30pcs*20jars",
    "BILLARDS GUMMY 8g*30pcs*20jars",
    "LADY BIRD GUMMY 8g*30pcs*20jars",
    "WATERMELON GUMMY 8g*30pcs*20jars",
    "Colour Candy Ball Stick 12gx40pcsx8vases",
    "5in1 Sour Powder 10gX50pcsx20boxes",
    "Birthday gummy 46gx6pcsx12box",
    "Marshmallow Hamburger Pop 18gx24pcsx12boxes",
    "harmonica Candy +fish Candy 3gx60pcsx12jars",
    "Skeleton Pop candy 7gx30pcsx24boxes",
    "Lighting Torch Candy 4.5gx20pcsx12boxes",
    "Animal shape + heart marshmallow stick 11gx30pcsx24boxes",
    "Skeleton Jelly 32gx70pcsx6jars",
    "Pizza Jelly Grape 50gx30pcsx10boxes",
    "Queen Cup Jelly (Strawberry) 100g x 8 pcs x 12tray",
    "Skateboard Crazy Hair candy 20gx20pcsx12boxes",
    "Cup Coffee Candy 15gx12pcsx12boxes",
    "Ice Cream Lolly Marshmallow 12gx30pcsx24boxes",
    "Ice Cream Popsicle Marshmallow 11gx30pcsx24boxes",
    "500g Macaron Cookies (Mixed Flavors) 500Gx 8Boxes",
    "LOLLIPOP MAXXI SOUR CHERRY 10X48X28G",
    "LOLLIPOP MAXXI WATERMELON 10X48X28G",
    "POP MANIA MAXXI GREEN APPLE 10X48X28G",
    "POP MANIA MAXXI RASPBERRY 10X48X28G",
    "POP MANIA MAXXI STRAWBERRY 10X48X28G",
    "SLIM TRANSPARENT EGG 6GR*6*12 army tank",
    "kokolin draje şek.kaplm.12*24*18gr choco punto",
    "Kokolin draje şeker kaplamalı 12*24*12gr PUNTO",
    "JELLYREX MIX 15g*12*24 JELLY CANDY",
    "Princess (Mini sandwich with strw cream) 900grx6",
    "BISCOLATA DUOMAX FINDIKLI 12KT 12AD 44G",
    "BISCOLATA DUOMAX SUTLU 12KT 12AD 44G",
    "CRAZY PRINC PATLAK AMB 6KT 24AD 30G KSA",
    "BOOMB. H.CV.KAR.PPT. 6KT12ADT35G CIS2",
    "TWINGO KARAMEL 6KT 24AD 42 CIS2",
    "WINERGY YER FISTIKLI BAR 6KT 24AD 30G",
    "BOOMBASTIC MARSH.BARKEK 6KT12AD40G UA/RU",
    "LUPPO DREAM BAR KAKAOLU 6KT12AD50G",
    "LUPPO DREAM BAR KARAMEL 6KT12AD50G",
    "OZMO CORNET SUTLU 25G 24 ADT 4KT",
    "OZMO CORNET MUZ-DRJ 25G 24ADT4KT TASO AZ",
    "OZMO CORNET G-DRJ 4KT24AD25G YD TASO",
    "OZMO CORNET CILEKLI 4KT24AD25G(AR-EN-RO)",
    "BISCOLATA MINIS FINDIKLI GOFRT 24PKT117G",
    "BOOMB. P.PTKLI FNDKLI GF 6KT12AD32G CIS2",
    "TRIPLEX KAPLAMALISZ 6KT 24AD 20G",
    "SOLEN LUPPO CAKE BITE DARK 12SP 184G(CS)",
    "LUPPO SANDVIC KAKKEK 6KT 24AD 25G LUBNAN",
    "LUPPO VISNE MAR.SNDVIC KEK 12SP 182G Y.T",
    "SOLEN LUPPO CAKE BITE SADE 12SP 184G(CS)",
    "LUPPO CAKEBITE CHOCO 6KT24AD25G (UA)",
    "LUPPO KARAMEL SNDVICKEK 12SP 182G BALKAN",
    "Luppo Red Velvet 12SP 182G",
    "BISCOLATA MOOD H.CEVZLI 24PK125G UA/RU",
    "OZMO BURGER 6KT 12ADT 40G IHRACAT CS2",
    "OZMO HOPPO CIK. 4KT*12ADT*40G ",
    "OZMO HOPPO CIK. 24PK 90G",
    "OZMO HOPPO CILEK 4KT12AD40G (Y.DES)",
    "BISC.MOOD NIGHT 24PK125G(BITTER) UA/RU",
    "BISCOLATA MOOD 24PK 115G",
    "PAPITA PARTY DRJ. SADE BISK 24AD 63G CIS",
    "PAPITA PARTY DRJ.KAKAOLU BIS24AD 63G CIS",
    "BISCOLATA STIX SUTLU 4KT 12AD 40G CIS2",
    "BISCOLATA STIX H.CEVIZ 4KT 12AD 32G()",
    "BISCOLATA STIX P.PATLAKLI 4KT 12AD 34G",
    "BISCOLATA STIX FINDIKLI 4KT 12AD 32G ()",
    "OZMO OGOPOGO CILEKLI KEK 4KT24AD30G",
    "OZMO OGOPOGO KAK KEK 4KT24AD30G CIS1",
    "OZMO FUN HAYVAN SERISI  4KT 24AD 23G",
    "OZMO FUN YILBASI 12KT24AD23G RTS RU/UA",
    "CHOCODANS KARAMEL 4KT12AD125G RUSYA OTO",
]

data_initial_dict = [
    {
        "text": "Diamond Light Candy 6gx24pcsx12boxes",
        "container_type": "box",
        "weight": 6,
        "weight_unit": "г",
        "pieces": 24,
        "containers": 12,
    },
    {
        "text": "POP MANIA MAXXI STRAWBERRY 10X48X28G",
        "container_type": "box",
        "weight": 28,
        "weight_unit": "г",
        "pieces": 48,
        "containers": 10,
    },
    {
        "text": "LUPPO DREAM BAR KAKAOLU 6KT12AD50G",
        "container_type": "box",
        "weight": 50,
        "weight_unit": "г",
        "pieces": 12,
        "containers": 6,
    },
    {
        "text": "BOOMBASTIC MARSH.BARKEK 6KT12AD40G UA/RU",
        "container_type": "box",
        "weight": 40,
        "weight_unit": "г",
        "pieces": 12,
        "containers": 6,
    },
    {
        "text": "WINERGY YER FISTIKLI BAR 6KT 24AD 30G",
        "container_type": "box",
        "weight": 30,
        "weight_unit": "г",
        "pieces": 24,
        "containers": 6,
    },
    {
        "text": "TWINGO KARAMEL 6KT 24AD 42 CIS2",
        "container_type": "box",
        "weight": 42,
        "weight_unit": "г",
        "pieces": 24,
        "containers": 6,
    },
    {
        "text": "BOOMB. H.CV.KAR.PPT. 6KT12ADT35G CIS2",
        "container_type": "box",
        "weight": 35,
        "weight_unit": "г",
        "pieces": 12,
        "containers": 6,
    },
    {
        "text": "CRAZY PRINC PATLAK AMB 6KT 24AD 30G KSA",
        "container_type": "box",
        "weight": 30,
        "weight_unit": "г",
        "pieces": 24,
        "containers": 6,
    },
    {
        "text": "BISCOLATA DUOMAX SUTLU 12KT 12AD 44G",
        "container_type": "box",
        "weight": 44,
        "weight_unit": "г",
        "pieces": 12,
        "containers": 12,
    },
    {
        "text": "BISCOLATA DUOMAX FINDIKLI 12KT 12AD 44G",
        "container_type": "box",
        "weight": 44,
        "weight_unit": "г",
        "pieces": 12,
        "containers": 12,
    },
    {
        "text": "Princess (Mini sandwich with strw cream) 900grx6",
        "container_type": "box",
        "weight": 900,
        "weight_unit": "г",
        "pieces": 1,
        "containers": 6,
    },
    {
        "text": "JELLYREX MIX 15g*12*24 JELLY CANDY",
        "container_type": "box",
        "weight": 15,
        "weight_unit": "г",
        "pieces": 12,
        "containers": 24,
    },
    {
        "text": "Kokolin draje şeker kaplamalı 12*24*12gr PUNTO",
        "container_type": "box",
        "weight": 12,
        "weight_unit": "г",
        "pieces": 24,
        "containers": 12,
    },
    {
        "text": "kokolin draje şek.kaplm.12*24*18gr choco punto",
        "container_type": "box",
        "weight": 18,
        "weight_unit": "г",
        "pieces": 24,
        "containers": 12,
    },
    {
        "text": "SLIM TRANSPARENT EGG 6GR*6*12 army tank",
        "container_type": "box",
        "weight": 6,
        "weight_unit": "г",
        "pieces": 6,
        "containers": 12,
    },
    {
        "text": "POP MANIA MAXXI RASPBERRY 10X48X28G",
        "container_type": "box",
        "weight": 28,
        "weight_unit": "г",
        "pieces": 48,
        "containers": 10,
    },
    {
        "text": "OZMO CORNET SUTLU 25G 24 ADT 4KT",
        "container_type": "box",
        "weight": 25,
        "weight_unit": "г",
        "pieces": 24,
        "containers": 4,
    },
    {
        "text": "POP MANIA MAXXI GREEN APPLE 10X48X28G",
        "container_type": "box",
        "weight": 28,
        "weight_unit": "г",
        "pieces": 48,
        "containers": 10,
    },
    {
        "text": "LOLLIPOP MAXXI WATERMELON 10X48X28G",
        "container_type": "box",
        "weight": 28,
        "weight_unit": "г",
        "pieces": 48,
        "containers": 10,
    },
    {
        "text": "LOLLIPOP MAXXI SOUR CHERRY 10X48X28G",
        "container_type": "box",
        "weight": 28,
        "weight_unit": "г",
        "pieces": 48,
        "containers": 10,
    },
    {
        "text": "500g Macaron Cookies (Mixed Flavors) 500Gx 8Boxes",
        "container_type": "box",
        "weight": 500,
        "weight_unit": "г",
        "pieces": 1,
        "containers": 8,
    },
    {
        "text": "Ice Cream Popsicle Marshmallow 11gx30pcsx24boxes",
        "container_type": "box",
        "weight": 11,
        "weight_unit": "г",
        "pieces": 30,
        "containers": 24,
    },
    {
        "text": "Ice Cream Lolly Marshmallow 12gx30pcsx24boxes",
        "container_type": "box",
        "weight": 12,
        "weight_unit": "г",
        "pieces": 30,
        "containers": 24,
    },
    {
        "text": "Cup Coffee Candy 15gx12pcsx12boxes",
        "container_type": "box",
        "weight": 15,
        "weight_unit": "г",
        "pieces": 12,
        "containers": 12,
    },
    {
        "text": "Skateboard Crazy Hair candy 20gx20pcsx12boxes",
        "container_type": "box",
        "weight": 20,
        "weight_unit": "г",
        "pieces": 20,
        "containers": 12,
    },
    {
        "text": "Queen Cup Jelly (Strawberry) 100g x 8 pcs x 12tray",
        "container_type": "tray",
        "weight": 100,
        "weight_unit": "г",
        "pieces": 8,
        "containers": 12,
    },
    {
        "text": "Pizza Jelly Grape 50gx30pcsx10boxes",
        "container_type": "box",
        "weight": 50,
        "weight_unit": "г",
        "pieces": 30,
        "containers": 10,
    },
    {
        "text": "Skeleton Jelly 32gx70pcsx6jars",
        "container_type": "jar",
        "weight": 32,
        "weight_unit": "г",
        "pieces": 70,
        "containers": 6,
    },
    {
        "text": "Animal shape + heart marshmallow stick 11gx30pcsx24boxes",
        "container_type": "box",
        "weight": 11,
        "weight_unit": "г",
        "pieces": 30,
        "containers": 24,
    },
    {
        "text": "Lighting Torch Candy 4.5gx20pcsx12boxes",
        "container_type": "box",
        "weight": 4.5,
        "weight_unit": "г",
        "pieces": 20,
        "containers": 12,
    },
    {
        "text": "LUPPO DREAM BAR KARAMEL 6KT12AD50G",
        "container_type": "box",
        "weight": 50,
        "weight_unit": "г",
        "pieces": 12,
        "containers": 6,
    },
    {
        "text": "OZMO CORNET MUZ-DRJ 25G 24ADT4KT TASO AZ",
        "container_type": "box",
        "weight": 25,
        "weight_unit": "г",
        "pieces": 24,
        "containers": 4,
    },
    {
        "text": "Ice Lolly Jelly 14gx30pcsx20boxes",
        "container_type": "box",
        "weight": 14,
        "weight_unit": "г",
        "pieces": 30,
        "containers": 20,
    },
    {
        "text": "OZMO HOPPO CIK. 24PK 90G",
        "container_type": "box",
        "weight": 90,
        "weight_unit": "г",
        "pieces": 24,
        "containers": 1,
    },
    {
        "text": "OZMO FUN YILBASI 12KT24AD23G RTS RU/UA",
        "container_type": "box",
        "weight": 23,
        "weight_unit": "г",
        "pieces": 24,
        "containers": 12,
    },
    {
        "text": "OZMO FUN HAYVAN SERISI  4KT 24AD 23G",
        "container_type": "box",
        "weight": 23,
        "weight_unit": "г",
        "pieces": 24,
        "containers": 4,
    },
    {
        "text": "OZMO OGOPOGO KAK KEK 4KT24AD30G CIS1",
        "container_type": "box",
        "weight": 30,
        "weight_unit": "г",
        "pieces": 24,
        "containers": 4,
    },
    {
        "text": "OZMO OGOPOGO CILEKLI KEK 4KT24AD30G",
        "container_type": "box",
        "weight": 30,
        "weight_unit": "г",
        "pieces": 24,
        "containers": 4,
    },
    {
        "text": "BISCOLATA STIX FINDIKLI 4KT 12AD 32G ()",
        "container_type": "box",
        "weight": 32,
        "weight_unit": "г",
        "pieces": 12,
        "containers": 4,
    },
    {
        "text": "BISCOLATA STIX P.PATLAKLI 4KT 12AD 34G",
        "container_type": "box",
        "weight": 34,
        "weight_unit": "г",
        "pieces": 12,
        "containers": 4,
    },
    {
        "text": "BISCOLATA STIX H.CEVIZ 4KT 12AD 32G()",
        "container_type": "box",
        "weight": 32,
        "weight_unit": "г",
        "pieces": 12,
        "containers": 4,
    },
    {
        "text": "BISCOLATA STIX SUTLU 4KT 12AD 40G CIS2",
        "container_type": "box",
        "weight": 40,
        "weight_unit": "г",
        "pieces": 12,
        "containers": 4,
    },
    {
        "text": "PAPITA PARTY DRJ.KAKAOLU BIS24AD 63G CIS",
        "container_type": "box",
        "weight": 63,
        "weight_unit": "г",
        "pieces": 24,
        "containers": 1,
    },
    {
        "text": "PAPITA PARTY DRJ. SADE BISK 24AD 63G CIS",
        "container_type": "box",
        "weight": 63,
        "weight_unit": "г",
        "pieces": 24,
        "containers": 1,
    },
    {
        "text": "BISCOLATA MOOD 24PK 115G",
        "container_type": "box",
        "weight": 115,
        "weight_unit": "г",
        "pieces": 24,
        "containers": 1,
    },
    {
        "text": "BISC.MOOD NIGHT 24PK125G(BITTER) UA/RU",
        "container_type": "box",
        "weight": 125,
        "weight_unit": "г",
        "pieces": 24,
        "containers": 1,
    },
    {
        "text": "OZMO HOPPO CILEK 4KT12AD40G (Y.DES)",
        "container_type": "box",
        "weight": 40,
        "weight_unit": "г",
        "pieces": 12,
        "containers": 4,
    },
    {
        "text": "OZMO HOPPO CIK. 4KT*12ADT*40G ",
        "container_type": "box",
        "weight": 40,
        "weight_unit": "г",
        "pieces": 12,
        "containers": 4,
    },
    {
        "text": "OZMO CORNET G-DRJ 4KT24AD25G YD TASO",
        "container_type": "box",
        "weight": 25,
        "weight_unit": "г",
        "pieces": 24,
        "containers": 4,
    },
    {
        "text": "OZMO BURGER 6KT 12ADT 40G IHRACAT CS2",
        "container_type": "box",
        "weight": 40,
        "weight_unit": "г",
        "pieces": 12,
        "containers": 6,
    },
    {
        "text": "BISCOLATA MOOD H.CEVZLI 24PK125G UA/RU",
        "container_type": "box",
        "weight": 125,
        "weight_unit": "г",
        "pieces": 24,
        "containers": 1,
    },
    {
        "text": "Luppo Red Velvet 12SP 182G",
        "container_type": "box",
        "weight": 182,
        "weight_unit": "г",
        "pieces": 12,
        "containers": 1,
    },
    {
        "text": "LUPPO KARAMEL SNDVICKEK 12SP 182G BALKAN",
        "container_type": "box",
        "weight": 182,
        "weight_unit": "г",
        "pieces": 12,
        "containers": 1,
    },
    {
        "text": "LUPPO CAKEBITE CHOCO 6KT24AD25G (UA)",
        "container_type": "box",
        "weight": 25,
        "weight_unit": "г",
        "pieces": 24,
        "containers": 6,
    },
    {
        "text": "SOLEN LUPPO CAKE BITE SADE 12SP 184G(CS)",
        "container_type": "box",
        "weight": 184,
        "weight_unit": "г",
        "pieces": 12,
        "containers": 1,
    },
    {
        "text": "LUPPO VISNE MAR.SNDVIC KEK 12SP 182G Y.T",
        "container_type": "box",
        "weight": 182,
        "weight_unit": "г",
        "pieces": 12,
        "containers": 1,
    },
    {
        "text": "LUPPO SANDVIC KAKKEK 6KT 24AD 25G LUBNAN",
        "container_type": "box",
        "weight": 25,
        "weight_unit": "г",
        "pieces": 24,
        "containers": 6,
    },
    {
        "text": "SOLEN LUPPO CAKE BITE DARK 12SP 184G(CS)",
        "container_type": "box",
        "weight": 184,
        "weight_unit": "г",
        "pieces": 12,
        "containers": 1,
    },
    {
        "text": "TRIPLEX KAPLAMALISZ 6KT 24AD 20G",
        "container_type": "box",
        "weight": 20,
        "weight_unit": "г",
        "pieces": 24,
        "containers": 6,
    },
    {
        "text": "BOOMB. P.PTKLI FNDKLI GF 6KT12AD32G CIS2",
        "container_type": "box",
        "weight": 32,
        "weight_unit": "г",
        "pieces": 12,
        "containers": 6,
    },
    {
        "text": "BISCOLATA MINIS FINDIKLI GOFRT 24PKT117G",
        "container_type": "box",
        "weight": 117,
        "weight_unit": "г",
        "pieces": 24,
        "containers": 1,
    },
    {
        "text": "OZMO CORNET CILEKLI 4KT24AD25G(AR-EN-RO)",
        "container_type": "box",
        "weight": 25,
        "weight_unit": "г",
        "pieces": 24,
        "containers": 4,
    },
    {
        "text": "Skeleton Pop candy 7gx30pcsx24boxes",
        "container_type": "box",
        "weight": 7,
        "weight_unit": "г",
        "pieces": 30,
        "containers": 24,
    },
    {
        "text": "harmonica Candy +fish Candy 3gx60pcsx12jars",
        "container_type": "jar",
        "weight": 3,
        "weight_unit": "г",
        "pieces": 60,
        "containers": 12,
    },
    {
        "text": "Marshmallow Hamburger Pop 18gx24pcsx12boxes",
        "container_type": "box",
        "weight": 18,
        "weight_unit": "г",
        "pieces": 24,
        "containers": 12,
    },
    {
        "text": "Super Car Gummy 20gx20pcsx12boxes",
        "container_type": "box",
        "weight": 20,
        "weight_unit": "г",
        "pieces": 20,
        "containers": 12,
    },
    {
        "text": "Birthday Cake Gummy 12gx20pcsx12boxes",
        "container_type": "box",
        "weight": 12,
        "weight_unit": "г",
        "pieces": 20,
        "containers": 12,
    },
    {
        "text": "Snake Gummy 8gx30pcsx20boxes",
        "container_type": "box",
        "weight": 8,
        "weight_unit": "г",
        "pieces": 30,
        "containers": 20,
    },
    {
        "text": "Long CC Stick Candy 4gx50pcsx40bags",
        "container_type": "bag",
        "weight": 4,
        "weight_unit": "г",
        "pieces": 50,
        "containers": 40,
    },
    {
        "text": "Biberon Liquid Candy 30mlX30pcsx18boxes",
        "container_type": "box",
        "weight": 30,
        "weight_unit": "мл",
        "pieces": 30,
        "containers": 18,
    },
    {
        "text": "EYEBALL CANDY SATND 3,5 GX24X8",
        "container_type": "box",
        "weight": 3.5,
        "weight_unit": "г",
        "pieces": 24,
        "containers": 8,
    },
    {
        "text": "EYE CANDY STAND 3,5 GX24X8",
        "container_type": "box",
        "weight": 3.5,
        "weight_unit": "г",
        "pieces": 24,
        "containers": 8,
    },
    {
        "text": "Bear Pudding 40gx20pcsx18tray",
        "container_type": "tray",
        "weight": 40,
        "weight_unit": "г",
        "pieces": 20,
        "containers": 18,
    },
    {
        "text": "Cow Eyes Gummy 7gx60pcsx12jars",
        "container_type": "jar",
        "weight": 7,
        "weight_unit": "г",
        "pieces": 60,
        "containers": 12,
    },
    {
        "text": "Cola Tin Spray Candy 30mlx24pcsx12boxes",
        "container_type": "box",
        "weight": 30,
        "weight_unit": "мл",
        "pieces": 24,
        "containers": 12,
    },
    {
        "text": "2in1 Crazy Hair Candy 20gx20pcsx12boxes",
        "container_type": "box",
        "weight": 20,
        "weight_unit": "г",
        "pieces": 20,
        "containers": 12,
    },
    {
        "text": "Crocodile jelly 35gx48pcsx6jars",
        "container_type": "jar",
        "weight": 35,
        "weight_unit": "г",
        "pieces": 48,
        "containers": 6,
    },
    {
        "text": "Snake jelly 35gx48pcsx6jars",
        "container_type": "jar",
        "weight": 35,
        "weight_unit": "г",
        "pieces": 48,
        "containers": 6,
    },
    {
        "text": "Toy and Jelly 30gx50pcsx6jars",
        "container_type": "jar",
        "weight": 30,
        "weight_unit": "г",
        "pieces": 50,
        "containers": 6,
    },
    {
        "text": "Dinosaur Gummy 8gx12pcsx20boxes",
        "container_type": "box",
        "weight": 8,
        "weight_unit": "г",
        "pieces": 12,
        "containers": 20,
    },
    {
        "text": "Birthday gummy 46gx6pcsx12box",
        "container_type": "box",
        "weight": 46,
        "weight_unit": "г",
        "pieces": 6,
        "containers": 12,
    },
    {
        "text": "5D Fruits Gummy Candy 10gx50pcsx12jars",
        "container_type": "jar",
        "weight": 10,
        "weight_unit": "г",
        "pieces": 50,
        "containers": 12,
    },
    {
        "text": "HOTDOG GUMMY 16g*24pcs*12boxes",
        "container_type": "box",
        "weight": 16,
        "weight_unit": "г",
        "pieces": 24,
        "containers": 12,
    },
    {
        "text": "COBRA GUMMY 16g*24pcs*12boxes",
        "container_type": "box",
        "weight": 16,
        "weight_unit": "г",
        "pieces": 24,
        "containers": 12,
    },
    {
        "text": "Baby bottle(Whistle candy) 9gx100pcsx6jars",
        "container_type": "jar",
        "weight": 9,
        "weight_unit": "г",
        "pieces": 100,
        "containers": 6,
    },
    {
        "text": "Winx Spray Candy 30gx12pcsx12boxes",
        "container_type": "box",
        "weight": 30,
        "weight_unit": "г",
        "pieces": 12,
        "containers": 12,
    },
    {
        "text": "Mini cup jlly (Benben bear Jar) 13gx100pcsx6jars",
        "container_type": "jar",
        "weight": 13,
        "weight_unit": "г",
        "pieces": 100,
        "containers": 6,
    },
    {
        "text": "Mini Jelly cup in (Trush can) 13gx100pcsx6jars",
        "container_type": "jar",
        "weight": 13,
        "weight_unit": "г",
        "pieces": 100,
        "containers": 6,
    },
    {
        "text": "Mini cup Jelly (Hippo Jar) 13gx100pcsx6jars",
        "container_type": "jar",
        "weight": 13,
        "weight_unit": "г",
        "pieces": 100,
        "containers": 6,
    },
    {
        "text": "Mini cup Jelly (Owl Jar) 13gx100pcsx6jars",
        "container_type": "jar",
        "weight": 13,
        "weight_unit": "г",
        "pieces": 100,
        "containers": 6,
    },
    {
        "text": "Mini cup Jelly (Duck Jar) 13gx100pcsx6jars",
        "container_type": "jar",
        "weight": 13,
        "weight_unit": "г",
        "pieces": 100,
        "containers": 6,
    },
    {
        "text": "Jelly cup in Koala Jar 13gx100pcsx6jars",
        "container_type": "jar",
        "weight": 13,
        "weight_unit": "г",
        "pieces": 100,
        "containers": 6,
    },
    {
        "text": "Mini Cup Jelly (Panda Bag) 13gx100pcsx6jars",
        "container_type": "jar",
        "weight": 13,
        "weight_unit": "г",
        "pieces": 100,
        "containers": 6,
    },
    {
        "text": "Jelly cup in Monkey Jar 13gx100pcsx6jars",
        "container_type": "jar",
        "weight": 13,
        "weight_unit": "г",
        "pieces": 100,
        "containers": 6,
    },
    {
        "text": "Jelly (Skeleton shape) 35gx55pcsx6jars",
        "container_type": "jar",
        "weight": 35,
        "weight_unit": "г",
        "pieces": 55,
        "containers": 6,
    },
    {
        "text": "Mini Jackpot Gum Ball 20gx12pcsx 12boxes",
        "container_type": "box",
        "weight": 20,
        "weight_unit": "г",
        "pieces": 12,
        "containers": 12,
    },
    {
        "text": "Bear Jelly 35gx30pcsx12boxes",
        "container_type": "box",
        "weight": 35,
        "weight_unit": "г",
        "pieces": 30,
        "containers": 12,
    },
    {
        "text": "Butterfly Jelly 35gx30pcsx12boxes",
        "container_type": "box",
        "weight": 35,
        "weight_unit": "г",
        "pieces": 30,
        "containers": 12,
    },
    {
        "text": "5in1 Sour Powder 10gX50pcsx20boxes",
        "container_type": "box",
        "weight": 10,
        "weight_unit": "г",
        "pieces": 50,
        "containers": 20,
    },
    {
        "text": "Colour Candy Ball Stick 12gx40pcsx8vases",
        "container_type": "vase",
        "weight": 12,
        "weight_unit": "г",
        "pieces": 40,
        "containers": 8,
    },
    {
        "text": "WATERMELON GUMMY 8g*30pcs*20jars",
        "container_type": "jar",
        "weight": 8,
        "weight_unit": "г",
        "pieces": 30,
        "containers": 20,
    },
    {
        "text": "LADY BIRD GUMMY 8g*30pcs*20jars",
        "container_type": "jar",
        "weight": 8,
        "weight_unit": "г",
        "pieces": 30,
        "containers": 20,
    },
    {
        "text": "BILLARDS GUMMY 8g*30pcs*20jars",
        "container_type": "jar",
        "weight": 8,
        "weight_unit": "г",
        "pieces": 30,
        "containers": 20,
    },
    {
        "text": "DEVIL GUMMY 8g*30pcs*20jars",
        "container_type": "jar",
        "weight": 8,
        "weight_unit": "г",
        "pieces": 30,
        "containers": 20,
    },
    {
        "text": "stick eyeball gummy 10g*30pcs*20jars",
        "container_type": "jar",
        "weight": 10,
        "weight_unit": "г",
        "pieces": 30,
        "containers": 20,
    },
    {
        "text": "Stick grape gummy 10g*30pcs*20jars",
        "container_type": "jar",
        "weight": 10,
        "weight_unit": "г",
        "pieces": 30,
        "containers": 20,
    },
    {
        "text": "Biberon liquit candy 40g*30pcs*16boxes",
        "container_type": "box",
        "weight": 40,
        "weight_unit": "г",
        "pieces": 30,
        "containers": 16,
    },
    {
        "text": "Toilet Candy 13gx24pcsx12boxes",
        "container_type": "box",
        "weight": 13,
        "weight_unit": "г",
        "pieces": 24,
        "containers": 12,
    },
    {
        "text": "Lighting New Spray Candy 25gx30pcsx20boxes",
        "container_type": "box",
        "weight": 25,
        "weight_unit": "г",
        "pieces": 30,
        "containers": 20,
    },
    {
        "text": "Bracelet Candy 10gx48pcsx12boxes UNI",
        "container_type": "box",
        "weight": 10,
        "weight_unit": "г",
        "pieces": 48,
        "containers": 12,
    },
    {
        "text": "Mega sour jam 30gx20pcsx12boxes",
        "container_type": "box",
        "weight": 30,
        "weight_unit": "г",
        "pieces": 20,
        "containers": 12,
    },
    {
        "text": "Microphone pudding 33gx30pcsx12jars",
        "container_type": "jar",
        "weight": 33,
        "weight_unit": "г",
        "pieces": 30,
        "containers": 12,
    },
    {
        "text": "Skull Candy + bear Candy 6gx60pcsx12jars",
        "container_type": "jar",
        "weight": 6,
        "weight_unit": "г",
        "pieces": 60,
        "containers": 12,
    },
    {
        "text": "Stretch frog candy 5gx12pcsx6boxes",
        "container_type": "box",
        "weight": 5,
        "weight_unit": "г",
        "pieces": 12,
        "containers": 6,
    },
    {
        "text": "Twins eyeball Gummy 4g*100pcs*12jars",
        "container_type": "jar",
        "weight": 4,
        "weight_unit": "г",
        "pieces": 100,
        "containers": 12,
    },
    {
        "text": "Roll Gum 7g×24pcs×24boxes",
        "container_type": "box",
        "weight": 7,
        "weight_unit": "г",
        "pieces": 24,
        "containers": 24,
    },
    {
        "text": "Big Foot lollipop+Sour Powder Candy 7.5gx30pcsx24boxes",
        "container_type": "box",
        "weight": 7.5,
        "weight_unit": "г",
        "pieces": 30,
        "containers": 24,
    },
    {
        "text": "Mini Lollipop Shooter 3gx12pcsx 24boxes",
        "container_type": "box",
        "weight": 3,
        "weight_unit": "г",
        "pieces": 12,
        "containers": 24,
    },
    {
        "text": "Big Burger Gummy 32gx8pcsx8boxes",
        "container_type": "box",
        "weight": 32,
        "weight_unit": "г",
        "pieces": 8,
        "containers": 8,
    },
    {
        "text": "Super Sour Hard Candy 12gx24pcsx20boxes",
        "container_type": "box",
        "weight": 12,
        "weight_unit": "г",
        "pieces": 24,
        "containers": 20,
    },
    {
        "text": "Fruits Press Candy 10gx30pcsx20boxes",
        "container_type": "box",
        "weight": 10,
        "weight_unit": "г",
        "pieces": 30,
        "containers": 20,
    },
    {
        "text": "Rabbit Candy 6gx30pcsx24trays",
        "container_type": "tray",
        "weight": 6,
        "weight_unit": "г",
        "pieces": 30,
        "containers": 24,
    },
    {
        "text": "Mouse Candy 6gx30pcsx24trays",
        "container_type": "tray",
        "weight": 6,
        "weight_unit": "г",
        "pieces": 30,
        "containers": 24,
    },
    {
        "text": "Ice Cream 3in1 16gx24pcsx10boxes",
        "container_type": "box",
        "weight": 16,
        "weight_unit": "г",
        "pieces": 24,
        "containers": 10,
    },
    {
        "text": "3in1 Squeeze Candy 45gx12pcsx12boxes",
        "container_type": "box",
        "weight": 45,
        "weight_unit": "г",
        "pieces": 12,
        "containers": 12,
    },
    {
        "text": "CHOCODANS KARAMEL 4KT12AD125G RUSYA OTO",
        "container_type": "box",
        "weight": 125,
        "weight_unit": "г",
        "pieces": 12,
        "containers": 4,
    },
]
